pipeline:
  test-syntax:
    image: alpine:latest
    commands:
      - apk update && apk add lua curl zip
      - find src -name '*.lua' -exec luac -p {} +

  package-love-dev:
    image: alpine:latest
    when:
      event: push
      branch: master
    commands:
      - export SYNTHEIN_VERSION=c${DRONE_COMMIT:8}
      - apk update && apk add zip
      - scripts/package-love.sh

  package-love-release:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - apk update && apk add zip
      - scripts/package-love.sh

  package-linux-appimage:
    image: ubuntu:14.04
    when:
      event: never
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apt-get update && apt-get install curl zip
      - scripts/package-linux-appimage.sh

  package-mac:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apk update && apk add curl zip
      - scripts/package-mac.sh

  package-windows:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apk update && apk add curl zip
      - scripts/package-windows.sh

  bad:
    image: alpine:latest
    when:
      event: push
      branch: telegram3
    commands:
      - echo ${TELEGRAM_TOKEN}

  telegram:
    image: appleboy/drone-telegram
    when:
      event: push
      branch: master
      status: [failure, success, error]
    token: "${TELEGRAM_TOKEN}"
    to: "-1001143861626"
    format: markdown
    message: >
      <strong>{{ uppercasefirst build.status }}</strong>
      <a href=\"{{ system.link_url }}/{{ repo.owner }}/{{ repo.name }}/{{ build.number }}\">{{ repo.owner }}/{{ repo.name }}</a>
      ({{ build.branch }}) by {{ build.author }}.
      <br>
      {{ build.message }}
