pipeline:
    test-syntax:
        when:
            event: push
        image: ubuntu:latest
        commands:
            - apt-get update && apt-get -y install lua5.3
            - find . -name '*.lua' -exec luac -p {} +
